
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftMASMENOSleftMULTDIVBASE CADENA CREATE DATA DIV ENTERO ID INTEGER MAS MENOS MULT PARA PARC PYC TABLE WHERE\n    ini : instrucciones\n    \n    instrucciones : instrucciones instruccion\n    \n    instrucciones : instruccion\n    \n    instruccion : crear_db\n                | crear_tb\n    \n    crear_db : CREATE DATA BASE ID PYC\n    \n    crear_tb : CREATE TABLE ID PARA PARC\n    '
    
_lr_action_items = {'CREATE':([0,2,3,4,5,7,14,15,],[6,6,-3,-4,-5,-2,-6,-7,]),'$end':([1,2,3,4,5,7,14,15,],[0,-1,-3,-4,-5,-2,-6,-7,]),'DATA':([6,],[8,]),'TABLE':([6,],[9,]),'BASE':([8,],[10,]),'ID':([9,10,],[11,12,]),'PARA':([11,],[13,]),'PYC':([12,],[14,]),'PARC':([13,],[15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ini':([0,],[1,]),'instrucciones':([0,],[2,]),'instruccion':([0,2,],[3,7,]),'crear_db':([0,2,],[4,4,]),'crear_tb':([0,2,],[5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ini","S'",1,None,None,None),
  ('ini -> instrucciones','ini',1,'p_inicio','parser.py',13),
  ('instrucciones -> instrucciones instruccion','instrucciones',2,'p_instrucciones','parser.py',20),
  ('instrucciones -> instruccion','instrucciones',1,'p_instrucciones_instruccion','parser.py',28),
  ('instruccion -> crear_db','instruccion',1,'p_instruccion','parser.py',34),
  ('instruccion -> crear_tb','instruccion',1,'p_instruccion','parser.py',35),
  ('crear_db -> CREATE DATA BASE ID PYC','crear_db',5,'p_crear_db','parser.py',41),
  ('crear_tb -> CREATE TABLE ID PARA PARC','crear_tb',5,'p_crear_tabla','parser.py',47),
]
