
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftMASMENOSleftMULTDIVBASE BIT CADENA COMA CREATE DATA DATE DATETIME DECIMAL DIV ENTERO ID INT KEY MAS MENOS MULT NCHAR NOT NULL NVARCHAR PARA PARC PRIMARY PYC TABLE WHERE\n    ini : instrucciones\n    \n    instrucciones : instrucciones instruccion\n    \n    instrucciones : instruccion\n    \n    instruccion : crear_db\n                | crear_tb\n    \n    crear_db : CREATE DATA BASE ID PYC\n    \n    crear_tb : CREATE TABLE ID PARA atributos PARC\n    \n    atributos : atributos COMA atributo\n              | atributo\n    \n    atributo : ID tipo atributo_opciones\n    \n    atributo_opciones : atributo_opciones atributo_opcion\n                      | atributo_opcion\n    \n    atributo_opcion : NOT NULL\n        | NULL\n        | PRIMARY KEY\n    \n    tipo : INT\n        | BIT\n        | DECIMAL\n        | DATE\n        | DATETIME\n        | NCHAR comp_n\n        | NVARCHAR comp_n\n    \n    comp_n : PARA ENTERO PARC\n    '
    
_lr_action_items = {'CREATE':([0,2,3,4,5,7,14,26,],[6,6,-3,-4,-5,-2,-6,-7,]),'$end':([1,2,3,4,5,7,14,26,],[0,-1,-3,-4,-5,-2,-6,-7,]),'DATA':([6,],[8,]),'TABLE':([6,],[9,]),'BASE':([8,],[10,]),'ID':([9,10,13,27,],[11,12,15,15,]),'PARA':([11,24,25,],[13,34,34,]),'PYC':([12,],[14,]),'INT':([15,],[19,]),'BIT':([15,],[20,]),'DECIMAL':([15,],[21,]),'DATE':([15,],[22,]),'DATETIME':([15,],[23,]),'NCHAR':([15,],[24,]),'NVARCHAR':([15,],[25,]),'PARC':([16,17,28,29,31,36,37,38,39,40,],[26,-9,-10,-12,-14,-8,-11,-13,-15,41,]),'COMA':([16,17,28,29,31,36,37,38,39,],[27,-9,-10,-12,-14,-8,-11,-13,-15,]),'NOT':([18,19,20,21,22,23,28,29,31,33,35,37,38,39,41,],[30,-16,-17,-18,-19,-20,30,-12,-14,-21,-22,-11,-13,-15,-23,]),'NULL':([18,19,20,21,22,23,28,29,30,31,33,35,37,38,39,41,],[31,-16,-17,-18,-19,-20,31,-12,38,-14,-21,-22,-11,-13,-15,-23,]),'PRIMARY':([18,19,20,21,22,23,28,29,31,33,35,37,38,39,41,],[32,-16,-17,-18,-19,-20,32,-12,-14,-21,-22,-11,-13,-15,-23,]),'KEY':([32,],[39,]),'ENTERO':([34,],[40,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ini':([0,],[1,]),'instrucciones':([0,],[2,]),'instruccion':([0,2,],[3,7,]),'crear_db':([0,2,],[4,4,]),'crear_tb':([0,2,],[5,5,]),'atributos':([13,],[16,]),'atributo':([13,27,],[17,36,]),'tipo':([15,],[18,]),'atributo_opciones':([18,],[28,]),'atributo_opcion':([18,28,],[29,37,]),'comp_n':([24,25,],[33,35,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ini","S'",1,None,None,None),
  ('ini -> instrucciones','ini',1,'p_inicio','parser.py',13),
  ('instrucciones -> instrucciones instruccion','instrucciones',2,'p_instrucciones','parser.py',20),
  ('instrucciones -> instruccion','instrucciones',1,'p_instrucciones_instruccion','parser.py',28),
  ('instruccion -> crear_db','instruccion',1,'p_instruccion','parser.py',34),
  ('instruccion -> crear_tb','instruccion',1,'p_instruccion','parser.py',35),
  ('crear_db -> CREATE DATA BASE ID PYC','crear_db',5,'p_crear_db','parser.py',41),
  ('crear_tb -> CREATE TABLE ID PARA atributos PARC','crear_tb',6,'p_crear_tabla','parser.py',47),
  ('atributos -> atributos COMA atributo','atributos',3,'p_atributos','parser.py',53),
  ('atributos -> atributo','atributos',1,'p_atributos','parser.py',54),
  ('atributo -> ID tipo atributo_opciones','atributo',3,'p_atributo','parser.py',61),
  ('atributo_opciones -> atributo_opciones atributo_opcion','atributo_opciones',2,'p_atributo_opciones','parser.py',67),
  ('atributo_opciones -> atributo_opcion','atributo_opciones',1,'p_atributo_opciones','parser.py',68),
  ('atributo_opcion -> NOT NULL','atributo_opcion',2,'p_atributo_opcion','parser.py',74),
  ('atributo_opcion -> NULL','atributo_opcion',1,'p_atributo_opcion','parser.py',75),
  ('atributo_opcion -> PRIMARY KEY','atributo_opcion',2,'p_atributo_opcion','parser.py',76),
  ('tipo -> INT','tipo',1,'p_tipo','parser.py',83),
  ('tipo -> BIT','tipo',1,'p_tipo','parser.py',84),
  ('tipo -> DECIMAL','tipo',1,'p_tipo','parser.py',85),
  ('tipo -> DATE','tipo',1,'p_tipo','parser.py',86),
  ('tipo -> DATETIME','tipo',1,'p_tipo','parser.py',87),
  ('tipo -> NCHAR comp_n','tipo',2,'p_tipo','parser.py',88),
  ('tipo -> NVARCHAR comp_n','tipo',2,'p_tipo','parser.py',89),
  ('comp_n -> PARA ENTERO PARC','comp_n',3,'p_comp_n','parser.py',95),
]
